### PR TITLE
fix: [component] send money buttons conditional disabled state

### LINKED ISSUE #21: Button "pay" should not be available if no account are available
In the store, the assumption that `.getAccounts()` will always give a result is wrong. The cyclos account can be deactivated, or no account has been yet set up. We should provide a sane page when no information can be displayed.

(see all mentions of `accounts[0]` in `lokapi.ts`)

### PR DESCRIPTION
**Pull request by seegwen**
make pay and recharge processes unavailable to the user which has no account

Should fix #21

### CODE REVIEW

**Review by stephansainleger — APPROVED** [review]
LGTM

**Comment by vaab** [comment]
- rebased to latest main without pain,
- added `(fixes #21)` at the end of the commit message.

Your test doesn't look if account is validated (just created and awaiting for validation) or no.

**Comment by vaab** [comment]
if you want to take quickly the rebased and renamed commit you'll find it on my remote (that you've already have configured I guess, and if not: 
```
git remote add vaab git@github.com:vaab/lokavaluto-web-application.git
git fetch vaab fix_no_accounts_available_in_store 
```
You can then jump on your branch

```
git stash ## if you had work ongoing
git co fix_no_accounts_available_in_store
git log -p  vaab/fix_no_accounts_available_in_store  ## to review my changes
git reset --hard vaab/fix_no_accounts_available_in_store  ## to move your branch to my proposed code and continue
```

**Comment by vaab** [comment]
I pushed the last version:
- Factorizing `computed`'s code to the store in a `getter`, 
- introduce usage of `mapGetters` and `mapState` in `YourAccs.vue` 
- I also used shortcut `:` instead of `v-bind`

Can you have a look and tell me if this is okay to you ? (code to see it is in previous message, or here:
 - first commit: https://github.com/vaab/lokavaluto-web-application/commit/41061cd1170911b4ed6e4c67936553521b1f85ef
 - second commit: https://github.com/vaab/lokavaluto-web-application/commit/0bfd1e304d60a1fdc978ee3710163123fc413a0e

**Comment by seegwen** [comment]
Yes, LGTM. Ca aurait pu faire l'objet d'une autre PR, mais c'est aussi bien que tu l'aie fait ici.
Tu as aussi changé un `"disabled"` en `:disabled="true"` ce qui fonctionne mais vu que true n'est pas réévalué, ce n'est pas nécessaire. J'imagine que tu as fait ça par souci de cohérence, et peut-être pour des développements futurs ?!

En tout cas c'est tout bon pour moi.

**Comment by vaab** [comment]
For the `disabled` stuff, well, I respectfully kept your change. I guess you did it for the reason you've given ;-) .
I've pushed your commits through my branch.

**Pull request closed without merging**
