### PR TITLE
create Wallet pages and process

### PR DESCRIPTION
**Pull request by seegwen**
Update from your stephan-admin-pages.
Took off the work that @stephansainleger did.

Added a backend handling
Added a form implementation with validation

Thing left to do is to connect the lokapi store to the real lokapi service, and erase the stubs.

I create this new PR because the other one #15 was way behind the main branch.

### CODE REVIEW

**Comment by vaab** [comment]
May I ask you to provide a clean list of commit (without merge commits). If you don't know how to make this easily, we can help. The main branch also was updated a little bit, so you'll need to rebase your current commits.

**Comment by vaab** [comment]
Nearly ! the first commit is still a `Merge` ... but I notice that everything else is straight and neat. This is what I did to fix the last issue:
```
git fetch https://github.com/seegwen/lokavaluto-web-application.git stephan-admin-pages  ## getting your commits
git checkout -b stephan-admin-pages fd91b24  ## f9d is the commit sha of the merge commit
git reset origin/main    ## keep every changes if any in the workdir, but move HEAD back to origin/main
git status  ## to check if there are actually some changes
```
There were no changes ! so the Merge commit is useless. Ok, then...
```
git cherry-pick fd91b24..FETCH_HEAD  ## fetch head is the last fetch
```
This last command asks to apply every commit diff starting from fd91b24 (the merge commit) to your last commit. 
Tada. A clean branch.

**Comment by vaab** [comment]
I had to change comments from french to english, in first commit (coming from stephan) and second.
- made a small change from `$store.hasUnconfiguredBackends()` -> `$store.hasUnconfiguredBackend()` to stay consistent with english, but also the local component `.hasUnconfiguredBackend()`. 
- I noticed that first commit is about admin pages, that should not be included in this PR, as the purpose of this PR is about the wallet creation page that is not an admin page.
- "Monetujo" -> "Monujo" in message to the user. The message is very nice, thanks !
- Not very sure when `$store.getBackendCredentials(..)` was supposed to be called as I can't find any call to it, and as a consequence `$store.credentials(..)`remains empty. After some thoughts, I don't think `state.availableBackend` is needed, thou I'm maybe missing the original intent here.
- checking if backend was configured was done in `$store` and again in `CreateWallet.vue`
- if disconnected, the page `CreateWallet.vue` would not redirect to login page, and would still display a seemingly valid form that could not work.
- Button to ask for account creation was linked to a missing function : `createTheWallet`.
- To aim at vocabulary unification, I renamed wallet -> account

**Comment by seegwen** [comment]
@seegwen is an action required on my part or is this all taken care of by you ?

**Comment by vaab** [comment]
@seegwen, nope, I took your commits and thanks to this PR did #45 , you can have a look at this PR and make a review if you feel like ;-)

**Pull request closed without merging**
