### PR TITLE
Fix components declarations

### PR DESCRIPTION
**Pull request by seegwen**
This one is a refactoring on all UI components to make the components definitions homogeneous.
There are also some fixes.
The commit messages are multiline and explain what was done to each file.

The branch to be merged was rebased on main prior to this PR, so they should automatically merge.

### CODE REVIEW

**Comment by vaab** [comment]
Thanks ! That's a great improvement to my eyes. I have an `Exception` while trying your code :
```
searchRecipients() Failed TypeError: _this3.$lokapi is undefined
    _callee4$ webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/components/sendAskMoney/SendAskMoney.vue?vue&type=script&lang=ts:238
    tryCatch webpack-internal:///../../js/lokapi-backend-comchain/node_modules/regenerator-runtime/runtime.js:63
    invoke webpack-internal:///../../js/lokapi-backend-comchain/node_modules/regenerator-runtime/runtime.js:294
    defineIteratorMethods webpack-internal:///../../js/lokapi-backend-comchain/node_modules/regenerator-runtime/runtime.js:119

```
Didn't really had time to look into it. I hope it doesn't come from me. Can you reproduce this issue ?

**Comment by vaab** [comment]
can you rebase and re-push directly the whole history with the fixed commits when you'll be done ? I'm thinking that the "Make component declaration..." commits are actually doing the same thing on multiple files. My feeling is that it should also be in one commit. For me commit separation is more about concerns than files. Do as you feel better on this latter topic.

**Comment by seegwen** [comment]
Yes, noted.
Moreover, the problem with this.$lokapi seems deeper than what I initially thought it was.

**Comment by seegwen** [comment]
I just checked. There are no components overlap.
I will fix the error inline, and add a commit which will take the lokapi out of the store into a service instantiation, in its own file.

**Comment by vaab** [comment]
Thanks a lot, this was really needed. The code smells fresher now. I have refactored the history and pushed your commits to main.

**Pull request closed without merging**
